# -*- coding: utf-8 -*-
"""hrv.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVrNBRCkB5XJ2ESJJLUHQDvIgg-yJQkw
"""

import os
import pandas as pd
import numpy as np
def calculate_HRV_metrics(file_in):
    df = pd.read_csv(file_in)
    df['time_next'] = df['time'].shift(-1)
    df['type_next'] = df['type'].shift(-1)
    df['rr'] = df['time_next'] - df['time']
    df['rr_type'] = df['type'] + df['type_next'].fillna('')
    df['rr_next'] = df['rr'].shift(-1)
    df['diff'] = df['rr_next'] - df['rr']
    df['diff_squared'] = df['diff'] ** 2
    df['rr_next_type'] = df['rr_type'].shift(-1)

    nn = df[df['rr_type'] == 'NN']
    n = len(nn)
    filename = os.path.basename(file_in)
    if n < 500:
        return {
            'filename': filename,
            'n': n,
            'mean_nn': None,
            'mean_bpm': None,
            'sdnn': None,
            'rmssd': None,
            'pnn20': None,
            'pnn50': None,
        }

    mean_nn = int(round(nn['rr'].mean()))
    mean_bpm = round((1000 / nn['rr'].mean()) * 60, 1)
    sdnn = round(nn['rr'].std(ddof=1), 1)
    nn_consec = df[(df['rr_type'] == 'NN') & (df['rr_next_type'] == 'NN')]
    rmssd = round(float(np.sqrt(nn_consec['diff_squared'].mean())), 1)
    pnn20 = round(float((np.abs(nn_consec['diff']) > 20).mean() * 100), 1)
    pnn50 = round(float((np.abs(nn_consec['diff']) > 50).mean() * 100), 1)

    return {
        'filename': filename,
        'n': n,
        'mean_nn': mean_nn,
        'mean_bpm': mean_bpm,
        'sdnn': sdnn,
        'rmssd': rmssd,
        'pnn20': pnn20,
        'pnn50': pnn50,
    }